apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: yourusername/my-simple-website
        ports:
        - containerPort: 80